# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj01model', '0003_query'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
        migrations.AlterModelTable(
            name='entry',
            table='entry',
        ),
    ]
